version: '3.5'

services:
  front:
    container_name: mw-mp-front
    build: .
    image: mw-mp-front
    networks:
      - mwnet
    restart: unless-stopped

networks:
  mwnet:
    name: mw-mp_mwnet
