name: Production front

on:
  push:
    branches:
      - 'master'

jobs:
  front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build front image
        run: docker build -t makewebme/mw-mp-front:latest . -f Dockerfile-prod

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push front image
        run: docker image push makewebme/mw-mp-front:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            rm -rf mw-mp-front
            git clone https://github.com/makewebme/mw-mp-front.git
            cd ./mw-mp-front
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            docker-compose -f docker-compose-prod.yml down
            docker-compose -f docker-compose-prod.yml up -d --build
            cd ..
            rm -rf mw-mp-front
